"use client";
import { ChangeEvent, useState } from "react";

type Letter={title:string;note:string;greeting:string;signature:string;message:string;stamp:string;icon:string;color:string;tilt:string;pdfName?:string};
const starter:Letter[]=[
{title:"Open when you feel sad",note:"For the days that feel a little too heavy.",greeting:"My love,",signature:"Always yours, Elise",message:"Some days arrive a little heavier than others. On those days, I hope these words remind you that you never have to carry everything alone. I am always with you, even from afar.",stamp:"WITH LOVE",icon:"☁",color:"gold",tilt:"left"},
{title:"Open when you miss me",note:"A small piece of me, folded up for you.",greeting:"My darling,",signature:"Missing you too, Elise",message:"If you are reading this, close your eyes and imagine I am right beside you. Distance cannot make what we have feel any less real.",stamp:"AIR MAIL",icon:"♥",color:"rose",tilt:"right"},
{title:"Open when you can't sleep",note:"For 2:17 a.m. and a restless heart.",greeting:"Hey sleepyhead,",signature:"Sweet dreams, Elise",message:"Let the day go. Nothing needs to be solved tonight. Breathe slowly, get cozy, and know that you are deeply loved.",stamp:"MOON POST",icon:"☾",color:"sage",tilt:"soft"},
{title:"Open when you need courage",note:"A reminder of everything you already are.",greeting:"My brave one,",signature:"I believe in you, Elise",message:"You have made it through every hard day that came before this one. Take the next small step. I am already so proud of you.",stamp:"PRIORITY",icon:"✦",color:"amber",tilt:"left"},
{title:"Open on your birthday",note:"Keep this one tucked away until your day.",greeting:"Birthday love,",signature:"All my love, Elise",message:"Today is for celebrating the wonderful person you are and every beautiful thing still waiting for you. I hope this year is gentle and bright.",stamp:"SPECIAL",icon:"✿",color:"blue",tilt:"right"},
{title:"Open when you need a laugh",note:"An emergency supply of ridiculousness.",greeting:"Okay, serious face off,",signature:"Your favourite comedian, Elise",message:"This is your official reminder that at least half our best memories started with a terrible idea. You must smile before closing this letter.",stamp:"EXPRESS",icon:"☺",color:"cream",tilt:"soft"}];

export default function Home(){
 const [letters,setLetters]=useState(starter),[editing,setEditing]=useState<number|null>(null),[draft,setDraft]=useState<Letter|null>(null),[saved,setSaved]=useState(false),[mode,setMode]=useState<"landing"|"sender"|"receiver">("landing"),[auth,setAuth]=useState<"signin"|"signup"|null>(null);
 const edit=(i:number)=>{setEditing(i);setDraft({...letters[i]});setSaved(false);window.scrollTo(0,0)};
 const add=()=>{setEditing(letters.length);setDraft({title:"Open when...",note:"A new little letter, waiting to be written.",greeting:"My love,",signature:"Always yours, Elise",message:"",stamp:"NEW POST",icon:"+",color:"gold",tilt:"soft"});setSaved(false);window.scrollTo(0,0)};
 const save=()=>{if(!draft||editing===null)return;setLetters(x=>editing<x.length?x.map((v,i)=>i===editing?draft:v):[...x,draft]);setSaved(true);setTimeout(()=>{setEditing(null);setDraft(null)},650)};
 const upload=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f&&draft)setDraft({...draft,pdfName:f.name})};
 if(mode==="landing")return <Landing preview={()=>setMode("receiver")} create={()=>setMode("sender")} auth={auth} setAuth={setAuth}/>;
 if(mode==="receiver")return <Receiver letters={letters} returnToSender={()=>setMode("sender")}/>;
 if(draft&&editing!==null)return <main className="editor-page">
  <header className="topbar editor-bar"><button className="back" onClick={()=>{setEditing(null);setDraft(null)}}>← <span>Back to collection</span></button><Brand/><span className="status"><i/> Draft saved</span></header>
  <section className="editor-shell">
   <aside className="controls"><span className="eyebrow">LETTER {String(editing+1).padStart(2,"0")}</span><h1>{editing<letters.length?"Edit your letter":"Write a new letter"}</h1><p className="helper">Make it personal. Your loved one will see this exactly as it appears on the paper.</p>
    <Field label="Letter title" value={draft.title} change={v=>setDraft({...draft,title:v})}/><Field label="Greeting" value={draft.greeting} change={v=>setDraft({...draft,greeting:v})}/><Field label="Signature" value={draft.signature} change={v=>setDraft({...draft,signature:v})}/>
    <div className="message-choice"><b>Choose how to add your message</b><label className="upload"><input type="file" accept="application/pdf" onChange={upload}/><strong>{draft.pdfName?"✓ PDF attached":"↑ Upload scanned letter"}</strong><small>{draft.pdfName||"PDF files only"}</small></label><div className="or"><span>or type it below</span></div><textarea rows={8} placeholder="Write from the heart..." value={draft.message} onChange={e=>setDraft({...draft,message:e.target.value})}/></div>
    <button className="save" onClick={save}>{saved?"Saved with love ♡":"Save letter"}<span>→</span></button>
   </aside>
   <div className="preview-wrap"><span className="preview-label">LIVE PREVIEW</span><article className="letter-paper"><div className="date">TORONTO · 14 FEBRUARY 2026</div><span className="kicker">{draft.title||"Your letter title"}</span><h2>{draft.greeting||"My love,"}</h2>{draft.pdfName?<div className="pdf"><span>PDF</span><b>{draft.pdfName}</b><small>Your scanned letter will appear here.</small></div>:<p className={"preview-message "+(!draft.message?"placeholder":"")}>{draft.message||"Your message will appear here as you type..."}</p>}<div className="signoff">{draft.signature||"Always yours, Elise"}</div></article></div>
  </section>
 </main>;
 return <main><header className="topbar"><Brand/><div className="top-actions"><span className="status"><i/> All changes saved</span><button className="outline" onClick={()=>setMode("receiver")}>Preview collection ↗</button></div></header>
  <section className="intro"><div><span className="postal">YOUR PRIVATE WRITING DESK <b>•</b> {letters.length} LETTERS</span><h1>Hi Elise,</h1><p>Let&apos;s build a letter collection for your loved one.</p></div><button className="new" onClick={add}><span>+</span> Add a new letter</button></section>
  <section className="desk"><div className="tape"/><p className="hand-note">Made with all my heart,<br/>for yours.</p><div className="grid">{letters.map((l,i)=><article className={"postcard "+l.tilt} key={i}><div className="pin">{i%2?"✦":"♥"}</div><div className={"stamp "+l.color}><span>{l.icon}</span><small>{l.stamp}</small></div><div className="postmark">TORONTO<br/><b>14 FEB</b><br/>2026</div><div className="post-lines"/><div className="copy"><span>LETTER {String(i+1).padStart(2,"0")}</span><h2>{l.title}</h2><p>{l.note}</p></div><button onClick={()=>edit(i)}><span>Edit letter</span><b>✎</b></button></article>)}<button className="add-card" onClick={add}><span>+</span><b>Add another letter</b><small>For one more moment that matters</small></button></div></section>
  <footer><span>LETTERS, KEPT FOR YOU</span><p>Your words, saved for exactly the right moment.</p><span>PRIVATE COLLECTION</span></footer>
  <button className="secret-toggle" onClick={()=>setMode("receiver")} aria-label="Secret receiver view" title="A little secret">L<span>♥</span></button>
 </main>
}
function Brand(){return <a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="mark">L</span><span><b>Letters,</b><em>kept for you</em></span></a>}
function Field({label,value,change}:{label:string,value:string,change:(v:string)=>void}){return <label className="field">{label}<input value={value} onChange={e=>change(e.target.value)}/></label>}

function Landing({preview,create,auth,setAuth}:{preview:()=>void;create:()=>void;auth:"signin"|"signup"|null;setAuth:(v:"signin"|"signup"|null)=>void}){
 return <main className="landing"><header className="topbar landing-bar"><Brand/><nav><button className="text-action" onClick={()=>setAuth("signin")}>Sign in</button><button className="outline filled" onClick={()=>setAuth("signup")}>Sign up</button></nav></header>
  <section className="landing-hero"><div className="landing-copy"><span className="postal">LOVE, DELIVERED AT THE RIGHT MOMENT</span><h1>Letters for the moments<br/><em>words matter most.</em></h1><p>Create a private collection of “Open When” letters for someone you love—written now, waiting for whenever they need you.</p><div className="hero-actions"><button className="primary-cta" onClick={create}>Create your collection <span>→</span></button><button className="preview-cta" onClick={preview}>Preview a collection <span>↗</span></button></div><small>Private by design · One link · Made with love</small></div>
   <div className="landing-stack" aria-label="A stack of handwritten Open When letters"><article className="hero-card back-card"><span>OPEN WHEN</span><h2>you need courage</h2></article><article className="hero-card middle-card"><span>OPEN WHEN</span><h2>you miss me</h2></article><article className="hero-card front-card"><div className="hero-stamp">♥<small>WITH LOVE</small></div><span>OPEN WHEN</span><h2>you feel sad</h2><p>A little piece of me,<br/>kept here for you.</p><b>Elise</b></article><div className="hero-seal">L<span>♥</span></div></div>
  </section>
  <section className="how"><span className="eyebrow">HOW IT WORKS</span><h2>Write once. Be there, again and again.</h2><div className="steps"><article><b>01</b><h3>Create your letters</h3><p>Type your message or upload a scanned handwritten letter.</p></article><article><b>02</b><h3>Share one private link</h3><p>Your loved one requests access once for the whole collection.</p></article><article><b>03</b><h3>Let each moment arrive</h3><p>Every letter waits until it is needed most.</p></article></div></section>
  <section className="landing-final"><div className="wax">L<span>♥</span></div><h2>Some things deserve<br/>more than a text message.</h2><button className="primary-cta" onClick={()=>setAuth("signup")}>Start writing <span>→</span></button></section>
  <footer><span>LETTERS, KEPT FOR YOU</span><p>A little corner of the internet, made with love.</p><span>EST. 2026</span></footer>
  {auth&&<div className="auth-backdrop" role="presentation" onClick={()=>setAuth(null)}><section className="auth-card" role="dialog" aria-modal="true" aria-labelledby="auth-title" onClick={e=>e.stopPropagation()}><button className="auth-close" onClick={()=>setAuth(null)} aria-label="Close">×</button><div className="wax small">L<span>♥</span></div><span className="eyebrow">{auth==="signup"?"BEGIN YOUR COLLECTION":"WELCOME BACK"}</span><h2 id="auth-title">{auth==="signup"?"Create your account":"Sign in to your letters"}</h2><p>{auth==="signup"?"Save your letters and share them with someone special.":"Continue writing or return to a collection shared with you."}</p><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary-cta" onClick={()=>{setAuth(null);create()}}>{auth==="signup"?"Create account":"Sign in"} <span>→</span></button><small>{auth==="signup"?"Already have an account? ":"New here? "}<button onClick={()=>setAuth(auth==="signup"?"signin":"signup")}>{auth==="signup"?"Sign in":"Create an account"}</button></small></section></div>}
 </main>
}

function Receiver({letters,returnToSender}:{letters:Letter[],returnToSender:()=>void}){
 const [opened,setOpened]=useState<number|null>(null);
 if(opened!==null){const letter=letters[opened];return <main className="receiver letter-open"><header className="topbar"><button className="back" onClick={()=>setOpened(null)}>← <span>All letters</span></button><Brand/><span className="status"><i/> Private letter</span></header><section className="receiver-paper-wrap"><article className="letter-paper readable"><div className="date">TORONTO · 14 FEBRUARY 2026</div><span className="kicker">{letter.title}</span><h2>{letter.greeting}</h2>{letter.pdfName?<div className="pdf"><span>PDF</span><b>{letter.pdfName}</b><small>Scanned letter attached with love.</small></div>:<p className="preview-message">{letter.message}</p>}<div className="signoff">{letter.signature}</div></article></section><button className="secret-toggle" onClick={returnToSender} aria-label="Secret sender view" title="Back to the writing desk">L<span>✎</span></button></main>}
 return <main className="receiver"><header className="topbar"><Brand/><div className="top-actions"><span className="status"><i/> Private collection</span><button className="outline">Sign in</button></div></header><section className="receiver-intro"><span className="postal">SPECIAL DELIVERY <b>•</b> A COLLECTION BY ELISE</span><h1>For all the moments<br/><em>I can&apos;t be there.</em></h1><p>Little letters, each one waiting for exactly the right moment to find you.</p><span className="awaits">↓ YOUR LETTERS AWAIT</span></section><section className="desk receiver-desk"><div className="grid">{letters.map((l,i)=><article className={"postcard "+l.tilt} key={i}><div className="pin">{i%2?"✦":"♥"}</div><div className={"stamp "+l.color}><span>{l.icon}</span><small>{l.stamp}</small></div><div className="postmark">TORONTO<br/><b>14 FEB</b><br/>2026</div><div className="post-lines"/><div className="copy"><span>LETTER {String(i+1).padStart(2,"0")}</span><h2>{l.title}</h2><p>{l.note}</p></div><button onClick={()=>setOpened(i)}><span>Open letter</span><b>→</b></button></article>)}</div></section><footer><span>LETTERS, KEPT FOR YOU</span><p>A little corner of the internet, made with love.</p><span>EST. 2026</span></footer><button className="secret-toggle" onClick={returnToSender} aria-label="Secret sender view" title="Back to the writing desk">L<span>✎</span></button></main>
}
